[package]
name = "nullad-intercept"
description = "NullAD interception layer: HTTP proxy, TLS SNI filter, DNS sinkhole."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nullad-engine.workspace = true
nullad-api.workspace = true
smallvec.workspace = true
tokio.workspace = true
futures-util.workspace = true
bytes.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http.workspace = true
http-body-util.workspace = true
httparse = "1"
psl = "2"
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pki-types.workspace = true
webpki-roots.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
